Codes of Lecture 00;
These files include hello.c(starter), vote.c(program to find person elligible to vote), average.c(program to take out average), score.c(to take out score of someone)...
These files are some beginner codes...

